version: "3.8"
services:
  postgres:
    image: "postgres:14"
    container_name: "java-postgres"
    environment:
      POSTGRES_DB: "client_db1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgre"
    ports:
        - "5432:5432"
  server:
   build:
     context: ./
     dockerfile: "server.Dockerfile"
   container_name: "java-server"
   environment:
      PORT: "8511"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/client_db1"
   ports:
     - "8511:8511"
   depends_on:
     - "postgres"
  client:
    build:
      context: ./
      dockerfile: "client.Dockerfile"
    container_name: "java-client"
    ports:
      - "8411:8411"









